### ISSUE TITLE
Tricky to distinguish matching paren from current paren

### ISSUE THREAD

**Issue by gauteh** [arzg/vim-colors-xcode#10]
Hi, thanks for the colors. I was wondering if it was possible to make it easier to distinguish matching parentheses, currently I perceive the matching parentheses more strongly than the current one and I keep getting confused about where the cursor is.

**Comment by arzg** [comment]
Hmm, Xcode uses the same yellow for matching parens but IMO doesn’t have this problem. I think it’s probably because Xcode removes the highlight of the matching paren after a second or so. [This can be achieved with vim-matchup](https://github.com/andymass/vim-matchup/issues/52).

Do you think it would be better to recommend users use matchup (with a specific configuration nonetheless) or to add an option to change the colour of the matching paren?

Also, do you find this issue occurs in all of the different variants, or just the dark ones (i.e. `xcodedark`, `xcodedarkhc`, and `xcodewwdc`)?

**Comment by davezuko** [comment]
Jumping in here to say the same. This is an absolutely lovely color scheme — thank you very much! — and I switched to it as I happened to be setting up a new machine. I say that because as I started coding, I noticed I was constantly confused with my cursor position, especially around adjacent parens/braces; at first thought maybe I'd misconfigured something, only to later realize it was the theme.

The light themes are definitely better in this regard. As far as a fix, I'll probably fiddle with the colors a bit to see how it might be improved, though I'm admittedly inexperienced with vim colorschemes. Hadn't heard of vim-matchup, so will check that out as well, though I don't think it should be necessary.

## Screenshots
Cursor is at the end of the last paren, but essentially invisible:

![Screen Shot 2020-02-28 at 10 03 42 AM](https://user-images.githubusercontent.com/6439050/75564803-6c3bf000-5a12-11ea-825f-5c5a6d4589c2.png)

Cursor is on the first paren, but difficult to distinguish what is what because the orange and yellow have equal strength.

![Screen Shot 2020-02-28 at 10 03 53 AM](https://user-images.githubusercontent.com/6439050/75564798-69d99600-5a12-11ea-9452-e22da47dcf01.png)

**Comment by gauteh** [comment]
Thanks for your replies. I already use vim-matchup, but not with any custom configuration. I have only tried with `xcodedark`. I think @davezuko hit the spot with the low contrast between cursor and matchparen color, I tried with a few other colorschemes and where I do not see this problem the matchparen color is much darker or less prominent. E.g. in gruvbox.

I realized just now on a different computer that a big factor is to turn off cursor blinking in the terminal, then I find it is easier to keep track.

I am in favor of trying out a different color for matchparen rather than using a custom matchup-configuration.

**Comment by arzg** [comment]
> the orange

I definitely see your point with the distinction between the yellow and the orange. Although I would say the recommended cursor colour for these colourschemes is the foreground text colour, if you were using this it would probably make the problem even worse!

I’ve just pushed a change that makes matchparens use the UI’s blue instead of yellow. I personally am yet to try out the vim-matchup config, but in case that ends up being better, I’ve added an option to get back the old behaviour.

**Comment by arzg** [comment]
@davezuko I noticed that you have some kind of Git information in your gutter. I’ve just added support for Signify to this colourscheme that makes it look very much like Xcode’s Git gutter. To get as close as possible, however, you need to add some configuration to your `vimdc` that I’ve listed in the README.

**Comment by gauteh** [comment]
I think the new colors work well! thanks!

**Comment by arzg** [comment]
Thanks :)

Do you think this issue can be closed now?

**Comment by gauteh** [comment]
Yes, for my part the issue is solved!

**Comment by davezuko** [comment]
Great improvement, @arzg — thanks for the ultra-fast turnaround. I also can't say how much I appreciate the added signify fixes. Feel free to close :).

**Comment by arzg** [comment]
No problem :)
