### ISSUE TITLE
Contrast is too low for some colors in dark mode

### ISSUE THREAD

**Issue by astyagun** [arzg/vim-colors-xcode#2]
Examples:

<img width="977" alt="Снимок экрана 2020-01-29 в 13 45 58" src="https://user-images.githubusercontent.com/158815/73350686-9331c580-429e-11ea-8b1f-894c329cbef5.png">

<img width="1027" alt="Снимок экрана 2020-01-29 в 13 49 30" src="https://user-images.githubusercontent.com/158815/73350861-e3a92300-429e-11ea-8a46-bacbde3585d4.png">

The way I solve it now: https://github.com/astyagun/.vim/commit/53b9368d73464ef0a733517261a29605b4becd8a. But it may be useful to change this in the colorscheme itself.

**Comment by arzg** [comment]
With regards to the visual selection, I personally find Xcode’s to be _too_ high contrast with the background for my liking – I actually find that it makes the text difficult to read. Would you be open to a sort of compromise, somewhere in between the two?

For the search highlights, on the other hand, vim-colors-xcode has support for [Searchlight](https://github.com/PeterRincker/vim-searchlight), which highlights the search match the cursor is on in the IncSearch highlight group (the one that appears around the current search match before you press enter on the search). I used the macOS blue accent colour for these rather than Xcode’s yellow because I wanted to avoid adding yet another colour to the palette, but I’m happy to add it if you think it will make it easier to use. I can see though that the search matches’ backgrounds seem to be brighter than vim-colors-xcode’s, so I might change that as well.

If my assumption that that is ObjC is correct, I would be happy to tune the highlighting the same way I’ve done for other languages too.

Also, I can’t help my self, but _oooh, JetBrains Mono._ Very similar to SF Mono, I might give it a try.

**Comment by astyagun** [comment]
> high contrast ... makes the text difficult to read

Does one need to read the text while it is selected? 🤔 For me it's often the case that I'm selecting text after I've already read it and have decided, that I want to do something with it.

But any increase in brightness of selection background would be welcome from my side 👏 With current brightness I often found myself squinting and moving closer to the monitor to confirm the shape of selection I've just made.

> Searchlight

Nice one, have installed it just now, thanks! This fixes the problem for the search match under the cursor.

> If my assumption that that is ObjC is correct, I would be happy to tune the highlighting the same way I’ve done for other languages too.

👍 

It's [this C++ file](https://github.com/astyagun/arduino-thermostat/blob/306e6b65b048145b024555f50b43fce55ebd1143/thermostat.cpp). Additionally highlighted by [this plugin](https://github.com/sudar/vim-arduino-syntax) (`filetype=arduino` based on `cpp` syntax).

> Also, I can’t help my self, but oooh, JetBrains Mono. Very similar to SF Mono, I might give it a try.

It does look good 👍 Stumbled upon it recently. Had to get rid of Powerline-style arrows in the status line in order to use it.

**Comment by arzg** [comment]
I just pushed a commit that increases the contrast of some UI elements. Could you take a look to see if this resolves your problem?

**Comment by astyagun** [comment]
Looks good 👍 Thank you!

**Comment by arzg** [comment]
No problem!
