### ISSUE TITLE
ALE Integration

### ISSUE THREAD

**Issue by kristijanhusak** [arzg/vim-colors-xcode#22]
Hi,

any chance to add [Ale](https://github.com/dense-analysis/ale) integration?

Some parts of it uses defaults, but some things are missing. For example, Neovim's virtual text is not highlighted at all.

Example screenshot with current highlights:
![screenshot](https://i.imgur.com/N6J2y9E.png)

And with added error highlight:
![screenshot-hl](https://i.imgur.com/PnguutJ.png)

Basically these two lines should be added:
```vimL
  hi link ALEVirtualTextError ErrorMsg
  hi link ALEVirtualTextWarning WarningMsg
```
Other things look like they're working.

**Comment by arzg** [comment]
I don’t use Vim any more, but I’m happy to add this. Working on it now.

**Comment by kristijanhusak** [comment]
Thanks.
Out of curiosity, what are you using now?

**Comment by arzg** [comment]
Currently I’m using VS Code. I switched because of [Rust Analyzer](https://github.com/rust-analyzer/rust-analyzer) (an LSP server for Rust).

Basically, I’ve always been a bit of a purist when it comes to my development tools, preferring to stick to the terminal with a fairly simple Vim setup. I always looked down on language intelligence, thinking that ‘Vim is good enough’. One day, I read [this awesome Reddit comment](https://www.reddit.com/r/rust/comments/fcshgy/why_do_you_think_intellij_is_a_good_development/fjd0ao6?utm_source=share&utm_medium=web2x&context=3) from the creator of Rust Analyzer, where he explains the benefits of language aware tooling. I had never even considered using them, as I had always dismissed them out of hand. In particular, my interest was piqued by this quote:

> However, I do believe that features, unlocked by deep understanding of the language, help. The funniest example here is extend/shrink selection. This features allows you to extend current selection to the next encompassing syntactic construct. It's the simplest feature an PostIntelliJ IDE can have, it only needs the parser. But it is sooo helpful when writing code, it just completely blows vim's text objects out of the water.

I decided to try VS Code, and although I switched to Vim and then decided to try VS Code again maybe ten times over the course of a month or three, it eventually stuck and I now can’t go back to Vim.

PS: yes, I’ve tried some language server plugins for (Neo)Vim, but IME they’re all inferior to VS Code.

**Comment by kristijanhusak** [comment]
Fair enough.
Not sure if you tried, but for `extend/shrink selection` you can try using https://github.com/nvim-treesitter/nvim-treesitter with it's [Incremental selection](https://github.com/nvim-treesitter/nvim-treesitter#incremental-selection). 
Works fairly ok with javascript, so I assume Rust works even better.

Thanks for adding this.

**Comment by arzg** [comment]
Thanks for the recommendation, but I think the only thing that can pull me back to Vim is feature parity between the Rust Analyzer experience on VS Code and on Vim.

Just a small aside: VS Code’s heavy footprint (1GB+ of memory usage at idle) and subpar text rendering when compared to native applications (plus a few other things) has inspired me to try making a GUI terminal/text editor hybrid thing. I doubt it’ll actually get anywhere, but I can dream :)

**Comment by kristijanhusak** [comment]
I guess you can watch for Onivim 2, they're trying to make that exact hybrid you're looking for :)
