### ISSUE TITLE
Cursorline's color isn't sky blue in xcodelight

### ISSUE THREAD

**Issue by ernestchu** [arzg/vim-colors-xcode#27]
As the title described, my cursorline remains grey. 

![Screen Shot 2021-04-17 at 8 13 36 AM](https://user-images.githubusercontent.com/51432514/115095708-cff5e500-9f54-11eb-96ec-bd03139fe181.png)

Is there a way or config option to fix this?

**Comment by arzg** [comment]
Do you have `termguicolors` enabled, as the readme’s ‘Usage’ section describes?

**Comment by ernestchu** [comment]
I've tried but it didn't work. I'm only Terminal.app in macOS 11 btw.

**Comment by arzg** [comment]
Unfortunately, Terminal.app is one of the few remaining terminal emulators that doesn’t support True Colour. You can either:

1. Live with the inaccurate colours
2. Switch to a different terminal emulator that does support True Colour (e.g. iTerm, Alacritty)
2. Switch to a colour scheme that limits itself to the constricted 256-colour palette Terminal.app offers. I don't know of any that are similar to xcodelight, so your options are:
  - use a completely different-looking theme that supports 256-colours, such as [Apprentice](https://github.com/romainl/Apprentice), [vim-corvine](https://github.com/arzg/vim-corvine) or [vim-colors-rusty](https://github.com/srijs/vim-colors-rusty). It's quite difficult to find themes that specifically use the 256-colour palette, so beware.
  - make your own colour scheme with [Colortemplate](https://github.com/lifepillar/vim-colortemplate)

Terminal.app has some other quirks relating to colours that mean I wouldn’t recommend it, even if you don’t end up needing True Colour:

- all colours are displayed slightly differently to their actual values (you can check this yourself by setting different colours of the colour palette to known values, and then checking what colour is actually displayed using the builtin Digital Color Meter.app
- when a bit of text has a specific background colour set, overriding the window background, the text _foreground_ is rendered slightly lighter than before
- when customising Terminal.app’s colour palette, the default colour space is Generic RGB instead of sRGB; essentially every colour hexcode you come across is in sRGB, so if you paste that in without first changing the colour space (it doesn’t remember the colour space you choose, so you have to remember to do that every single time) it’ll render a bit differently (either lighter or darker, I can’t remember) to what you intended as it’s using Generic RGB instead of sRGB

Sorry for the rant; as you might guess I’ve spent a long time debugging my colour schemes, wondering why they display slightly wrong in Terminal.app when compared to other terminal emulators, and have unfortunately found bugs that seem like they’ve been present ever since 256-colour support was added way back in OS X Lion.

Let me know what you decide to do :)

**Comment by ernestchu** [comment]
Thanks for the rich explanation! I guess I'll live with the grey cursor line. Great work on this project!

**Comment by nachovizzo** [comment]
I'm using iTerm2 and also face the same error, anyone else?

I enabled termguicolors

**Comment by nachovizzo** [comment]
I'm using iTerm2 and also face the same error, anyone else?

I enabled termguicolors

**Comment by lunacookies** [comment]
Would you mind creating a new issue for this to avoid notification spam?

**Comment by nachovizzo** [comment]
I have a fix, if you are interested, I can open a PR. Otherwise, I guess we could leave it here. It's up to the maintainers
